### ISSUE TITLE
PDF of the schematic

### ISSUE THREAD

**Issue by nrivard** [floobydust/C02-Pocket-SBC#1]
Very cool project (I found it from the 6502 forums) but is it possible to export the hardware schematic to PDF? I am a KiCADer but want to at least view the schematic.

**Comment by floobydust** [comment]
Hopefully you received the image file I sent you earlier... if that didn't work, let me know.

**Comment by nrivard** [comment]
Hi Flooby, I did not receive it. How was it sent?

**Comment by floobydust** [comment]
Hi Nate, I replied to the initial email. Apparently that doesn't work, so I opted to add the BMP (standard bitmap) file to the Hardware folder. Hope this works. - KM

**Comment by nrivard** [comment]
Yep this is great, thank you!
